name: terraform-plan-eval
on:
  pull_request:
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Plan (EVAL)
        run: |
          echo "EVAL: plan-only pipeline placeholder"
          echo "EVAL: evidence placeholder (plan.json in container output)"